### PR TITLE
#162948904 Heroku Hosting

### PR DESCRIPTION
**Pull request by tesh254**
#### What does this PR do?

This PR contains the configuration for the application to be remotely hosted online.

#### Description of Task(s) to be completed?

* Introduce `Procfile` file to hold Heroku hosting config.
* Install `django-heroku` to hold the static files
* Introduce the `gunicorn` package to run the Django app.

#### How should this be manually tested?

* [Click Here](https://ah-alpha.herokuapp.com/) to copy URL and manually test on postman

#### What are the relevant pivotal tracker stories?

* [#162948896](https://www.pivotaltracker.com/story/show/162948896)

### CODE REVIEW

**Review by boltonotieno — APPROVED** [review]
The links works and the structure of the PR is good- Simple and detailed

**Review by danuluma — APPROVED** [review]

**Comment by danuluma** [comment]
Great. It's working

**Review by Ruiru11 — APPROVED** [review]

**Comment by frankip** [comment]
@tesh254 good work on the PR however for the commit message we had agreed to use delivers instead of finishes

**Comment by tesh254** [comment]
> @tesh254 good work on the PR however for the commit message we had agreed to use delivers instead of finishes

Noted

**Pull request merged**
